---
abstract: "configure-time utilities for using C headers,\nlibraries, or OS features"
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Module::Build: 0
  Test::Fatal: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-CChecker
provides:
  ExtUtils::CChecker:
    file: lib/ExtUtils/CChecker.pm
    version: 0.08
requires:
  ExtUtils::CBuilder: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
